### ISSUE TITLE
RISCV cargo fault

### ISSUE THREAD

**Issue by chaozju** [nix-rust/nix#1253]
I am working cross-compiling [wasmer](https://github.com/wasmerio/wasmer) to RISCV within which nix is used.

After assigning 
```toml
nix =  "0.17.0"
# or
nix = { version = "0.17.0", git = "https://github.com/nix-rust/nix", rev = "7696559b921eace963bd9f01a40c6cf442298e82"}

```
then
```bash
cargo update
cargo build --some-flag
```
Then I still get things like 
```bash
error[E0425]: cannot find value `PTRACE_GETFPXREGS` in crate `libc`
   --> /home/chao/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.17.0/src/sys/ptrace/linux.rs:84:9
    |
84  |         PTRACE_GETFPXREGS,
    |         ^^^^^^^^^^^^^^^^^
```

I can still get wrong result  as following (which is different from code in this repo now)checking crate code
```bash
chao@DESKTOP-B79IRTG:~/wasmer$ cat ~/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.17.0/src/sys/ptrace/linux.rs | grep riscv
                                               target_arch = "riscv64",
                                               target_arch = "riscv64",
                                               target_arch = "riscv64",
                                               target_arch = "riscv64",
                                           target_arch = "riscv64")))]
                                           target_arch = "riscv64")))]
```
