### ISSUE TITLE
MacOS: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by PsiACE** [nix-rust/nix#1588]
= note: Undefined symbols for architecture x86_64:
            "_preadv", referenced from:
                nix::sys::uio::preadv::h8c66d9fb8b619a73 in libnix-1b7d7137231b30ff.rlib(nix-1b7d7137231b30ff.nix.1b5c8824-cgu.0.rcgu.o)
            "_pwritev", referenced from:
                nix::sys::uio::pwritev::hb39f620af1eb34cc in libnix-1b7d7137231b30ff.rlib(nix-1b7d7137231b30ff.nix.1b5c8824-cgu.0.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by asomers** [comment]
What command results in that error?  What version of OSX are you using?  And, if you know, why doesn't this happen in CI?

**Comment by PsiACE** [comment]
> What command results in that error? 

```
      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          components: rustfmt
          args: --all-features --no-fail-fast
        env:
          RUST_TEST_THREADS: 2
          RUST_LOG: debug
          RUST_BACKTRACE: full
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'
```

> What version of OSX are you using? 

`macos-latest`

> And, if you know, why doesn't this happen in CI?

This happen in CI.
