### ISSUE TITLE
Docs are not being updated in S3

### ISSUE THREAD

**Issue by kamalmarhubi** [nix-rust/nix#320]
Compare, for example:

rustdoc.s3-website-us-east-1.amazonaws.com/nix/master/linux/src/nix/sys/uio.rs.html
https://github.com/nix-rust/nix/blob/master/src/sys/uio.rs

The S3 version is missing the fact that #304 got rid of `mod ffi` in that module.

**Comment by posborne** [comment]
Homm, problem is probably the repo line? https://github.com/nix-rust/nix/blob/master/.travis.yml#L72

```yaml
  on:
    condition: "\"$TRAVIS_RUST_VERSION/$ARCH\" == \"1.1.0/x86_64\""
    repo: carllerche/nix-rust
    branch:
      - master
```
